// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Xyz
{
    [XyzResourceType("xyz:index:RandomLogin")]
    public partial class RandomLogin : global::Pulumi.ComponentResource
    {
        [Output("password")]
        public Output<string> Password { get; private set; } = null!;

        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a RandomLogin resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RandomLogin(string name, RandomLoginArgs args, ComponentResourceOptions? options = null)
            : base("xyz:index:RandomLogin", name, args ?? new RandomLoginArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class RandomLoginArgs : global::Pulumi.ResourceArgs
    {
        [Input("passwordLength", required: true)]
        public Input<int> PasswordLength { get; set; } = null!;

        [Input("petName", required: true)]
        public bool PetName { get; set; }

        public RandomLoginArgs()
        {
        }
        public static new RandomLoginArgs Empty => new RandomLoginArgs();
    }
}
