// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RandomLogin extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'xyz:index:RandomLogin';

    /**
     * Returns true if the given object is an instance of RandomLogin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RandomLogin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RandomLogin.__pulumiType;
    }

    public /*out*/ readonly password!: pulumi.Output<string>;
    public readonly passwordLength!: pulumi.Output<number>;
    public readonly petName!: pulumi.Output<boolean>;
    public /*out*/ readonly username!: pulumi.Output<string>;

    /**
     * Create a RandomLogin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RandomLoginArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.passwordLength === undefined) && !opts.urn) {
                throw new Error("Missing required property 'passwordLength'");
            }
            if ((!args || args.petName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'petName'");
            }
            resourceInputs["passwordLength"] = args ? args.passwordLength : undefined;
            resourceInputs["petName"] = args ? args.petName : undefined;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        } else {
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["passwordLength"] = undefined /*out*/;
            resourceInputs["petName"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RandomLogin.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a RandomLogin resource.
 */
export interface RandomLoginArgs {
    passwordLength: pulumi.Input<number>;
    petName: pulumi.Input<boolean>;
}
